### ISSUE TITLE
Can we archive this project?

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/discord-server-info#16]
cc @with-heart @myz1237

**Comment by with-heart** [comment]
Nope! It's going to be a slow roll for the time being but it's on my list of projects to tackle

**Comment by kempsterrrr** [comment]
That was an easy one ❤️  LGTM

**Comment by myz1237** [comment]
> cc @with-heart @myz1237

Just keep it, I am working on the bot and database part
